### ISSUE TITLE
Impossible de lancer le serveur API

### ISSUE THREAD

**Issue by HenriMichelonEsimed** [fmarin84/Node_js#1]
`> node main.js
(node:1136) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dao' of undefined
    at C:\Users\hmich\OneDrive - esimed.fr\Rendus exams et projets\2020\JavaScript\marin\API\datamodel\seeder.js:10:32
`

**Comment by fmarin84** [comment]
Bug résolut
